import type { MappingRow } from './workbook';

// ponytail: 預設 Management_Mapping 規則，來自 Management_Mapping.xlsx
// 使用者可上傳新版覆蓋
export const DEFAULT_MAPPING: MappingRow[] = [
  { Original_Item_Name: 'AAG070_CKBD_DR_Check_SHARE_(M)', Mode: 'DR', Operation: 'DR' },
  { Original_Item_Name: 'Auto_Page_PGM_(M)', Mode: 'TM PGM', Operation: 'PULSE PGM' },
  { Original_Item_Name: 'BM_Margin_Read2B_Dual_4M2BPAT_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'BM_Margin_Read_4M2BPAT_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'BM_Margin_Read_Dual_4M2BPATCR_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'BM_Margin_Read_Dual_4M2BPAT_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'BM_Page_Program_4M2BPATCR_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'BM_Page_Program_4M2BPAT_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'BM_Page_QuadProgram_4M2BPAT_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'BM_Quad_Read_4M2BPAT_(M)', Mode: 'UM READ', Operation: 'QUAD READ' },
  { Original_Item_Name: 'Block_2Page_PGM_AA55_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Block_2Page_PGM_DSL_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Block_2Page_PGM_F00F_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Block_2Page_PGM_FF00_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Block_Erase_KGD_(M)', Mode: 'UM ERS', Operation: 'BLK ERS' },
  { Original_Item_Name: 'Block_Erase_RSR_(M)', Mode: 'UM ERS', Operation: 'BLK ERS' },
  { Original_Item_Name: 'Block_Erase_RSR_4BAM_(M)', Mode: 'UM ERS', Operation: 'BLK ERS' },
  { Original_Item_Name: 'Block_Erase_SlewRate_RSR_(M)', Mode: 'UM ERS', Operation: 'BLK ERS' },
  { Original_Item_Name: 'CAMCell_EVAll_ERS_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'CAMCell_EVAll_ERS_IBLK_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'CAMCell_Erase_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'CAMCell_Erase_IBLK_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'CAM_PGM_PV_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'CAM_PGM_PV_DR_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'CAM_PGM_PV_IBLK_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'CAM_PGM_PV_IBLK_DR_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Check_BE_PerStep_cyc_time_(M)', Mode: 'CHECK ERS TIME', Operation: 'CHECK ERS TIME' },
  { Original_Item_Name: 'Check_BE_PerStep_cyc_time_128M_(M)', Mode: 'CHECK ERS TIME', Operation: 'CHECK ERS TIME' },
  { Original_Item_Name: 'Check_DR_Outlier_bit_CKBD_0_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Check_DR_Outlier_bit_CKBD_1_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Check_DataHVP_Vg_(M)', Mode: 'CHECK VT', Operation: 'CHECK VT' },
  { Original_Item_Name: 'Check_Data_Vg_(M)', Mode: 'CHECK VT', Operation: 'CHECK VT' },
  { Original_Item_Name: 'Check_EraseStep_Time_(M)', Mode: 'CHECK ERS TIME', Operation: 'CHECK ERS TIME' },
  { Original_Item_Name: 'Check_Erase_Time_(M)', Mode: 'CHECK ERS TIME', Operation: 'CHECK ERS TIME' },
  { Original_Item_Name: 'Check_Erase_Time_New_(M)', Mode: 'CHECK ERS TIME', Operation: 'CHECK ERS TIME' },
  { Original_Item_Name: 'Check_Final_Info_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'Check_Final_Info_IBLK_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'Check_Final_Info_IBLK_external_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'Check_Final_Info_external_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'Check_ID_Info_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'Check_Manual_Erase_Up_(M)', Mode: 'CHECK MERS', Operation: 'CHECK MERS' },
  { Original_Item_Name: 'Check_Margin_Read_Dual_RBLK_(M)', Mode: 'MR', Operation: 'MR RBLK' },
  { Original_Item_Name: 'Check_Margin_Read_RBLK_(M)', Mode: 'MR', Operation: 'MR RBLK' },
  { Original_Item_Name: 'Check_OPT_Info_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_OptionBit_EV_IBLK_KGD_DG_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_OptionBit_EV_IBLK_KGD_DG_Final_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_OptionBit_EV_KGD_DG_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_OptionBit_EV_KGD_DG_Finial_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_OptionBit_EV_KGD_SFIN_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_OptionBit_EV_ReS_RBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_OptionBit_PV_IBLK_KGD_DG_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_OptionBit_PV_IBLK_KGD_DG_Final_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_OptionBit_PV_KGD_DG_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_OptionBit_PV_KGD_DG_Finial_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_OptionBit_PV_KGD_SFIN_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_OptionBit_Read_IBLK_KGD_DG_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_OptionBit_Read_KGD_DG_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Check_Outlier_bit_0_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Check_Outlier_bit_1_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Check_Outlier_bit_1_ECC_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Check_Outlier_bit_CKBD_0_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Check_Outlier_bit_CKBD_0_ECC_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Check_RA_Repair_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'Check_RDN_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'Check_RDN_4BAM_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'Check_RDN_AAG070_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'Check_RDN_FAG089_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'Check_RDN_Margin_Read_RBLK_(M)', Mode: 'MR', Operation: 'MR RBLK' },
  { Original_Item_Name: 'Check_RDN_Margin_Read_RBLK_4BAM_(M)', Mode: 'MR', Operation: 'MR RBLK' },
  { Original_Item_Name: 'Check_RefCell_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'Check_S1P1_Outliner_ALL0_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Check_S1P1_Outliner_ALL0_ECC_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Check_UV_(M)', Mode: 'CHECK UV', Operation: 'CHECK UV' },
  { Original_Item_Name: 'Check_VPPD_(M)', Mode: 'MONITOR', Operation: 'MONITOR' },
  { Original_Item_Name: 'Check_VPPI_(M)', Mode: 'MONITOR', Operation: 'MONITOR' },
  { Original_Item_Name: 'Check_Vref_(M)', Mode: 'MONITOR', Operation: 'MONITOR' },
  { Original_Item_Name: 'Check_blk_6E_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Check_blk_ECC_6E_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Chip_Erase_KGD_(M)', Mode: 'UM ERS', Operation: 'CHIP ERS' },
  { Original_Item_Name: 'Chip_Erase_RSR_(M)', Mode: 'UM ERS', Operation: 'CHIP ERS' },
  { Original_Item_Name: 'D4B80D_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'D4B8ED_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'D4BD0D_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'D4BDBD_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'D4BDED_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DIOMID_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DLP_Program_FT_Data_RSR_(M)', Mode: 'UM MINI', Operation: 'SFDP WR' },
  { Original_Item_Name: 'DLP_Read_FT_Data_RSR_(M)', Mode: 'UM MINI', Operation: 'SFDP WR' },
  { Original_Item_Name: 'DR3X3B1_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DR3X3B2_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DR3X3B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DR3X3B_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DR3XBB1_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DR3XBB2_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DR3XBB_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DR3XBB_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DR4B3B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DR4B3C_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DR4BBB_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DR4BBC_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DR_CKBD_Check_SHARE_(M)', Mode: 'DR', Operation: 'DR' },
  { Original_Item_Name: 'DR_CKBD_Check_SHARE_20Mhz_(M)', Mode: 'DR', Operation: 'DR' },
  { Original_Item_Name: 'DS03_ALL0_DR_Outlier_Check_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'DS03_ALL0_DR_Outlier_Check_NEW_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'DS03_Fail_Retest_(M)', Mode: 'FAIL RETEST', Operation: 'FAIL RETEST' },
  { Original_Item_Name: 'DS03_IFR_Mark_IBLK_MDUT_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'DS03_IFR_Mark_MDUT_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'DS03_Pass_Mark_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'DS03_ReFresh_OptionBit_IFR_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'DS03_ReFresh_OptionBit_IFR_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'DS05_Fail_Retest_(M)', Mode: 'FAIL RETEST', Operation: 'FAIL RETEST' },
  { Original_Item_Name: 'DS05_IFR_Mark_IBLK_MDUT_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'DS05_IFR_Mark_MDUT_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'DS05_Pass_Mark_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'DS05_ReFresh_OptionBit_IFR_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'DS05_ReFresh_OptionBit_IFR_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'DT480E_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTR10ED1_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTR10ED2_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTR80D_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTR80E_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTR8ED1_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTR8ED2_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTR8ED_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRD0D1_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRD0D2_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRD0D_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRD0D_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRD0E_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRDBD1_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRDBD2_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRDBD_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRDBD_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRDBE_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRDED1_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRDED2_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRDED_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'DTRDED_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Data_Retention_Check_(M)', Mode: 'DR', Operation: 'DR' },
  { Original_Item_Name: 'Device_ID_(M)', Mode: 'ID', Operation: 'ID READ' },
  { Original_Item_Name: 'Device_ID_DIO_KGD_(M)', Mode: 'ID', Operation: 'ID READ' },
  { Original_Item_Name: 'Device_ID_KGD_(M)', Mode: 'ID', Operation: 'ID READ' },
  { Original_Item_Name: 'Device_ID_KGD_NOPD_(M)', Mode: 'ID', Operation: 'ID READ' },
  { Original_Item_Name: 'Diag_Margin_Read_DBM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Diag_Margin_Read_Dual_DBM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Drain_Stress_All_(M)', Mode: 'STRESS', Operation: 'BL STRESS' },
  { Original_Item_Name: 'Drain_Stress_All_2M_(M)', Mode: 'STRESS', Operation: 'BL STRESS' },
  { Original_Item_Name: 'Drain_Stress_All_2M_NEW_(M)', Mode: 'STRESS', Operation: 'BL STRESS' },
  { Original_Item_Name: 'ECC_Decoder_Check_(M)', Mode: 'ECC ENGINE', Operation: 'ECC Decoder' },
  { Original_Item_Name: 'ECC_Decoder_Compression_(M)', Mode: 'ECC ENGINE', Operation: 'ECC Decoder' },
  { Original_Item_Name: 'ECC_Encoder_Check_(M)', Mode: 'ECC ENGINE', Operation: 'ECC Decoder' },
  { Original_Item_Name: 'ECC_Encoder_Compression_(M)', Mode: 'ECC ENGINE', Operation: 'ECC Decoder' },
  { Original_Item_Name: 'ECC_Repair_Algorithm_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'ECC_Repair_Algorithm_CAT3L_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'ECC_Repair_Algorithm_CAT6E_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'ECC_Repair_Algorithm_CAT6E_1_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'ECC_Repair_Analysis_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'EI3B44_(M)', Mode: 'UM MINI', Operation: 'IBLK WR' },
  { Original_Item_Name: 'EOBLKMargin_Read_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'EOBLKMargin_Read_4BAM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'EOBLKMargin_Read_Dual_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'EOBLK_TACCR_Margin_Read_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'EOBLK_TACCR_Margin_Read_Dual_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'EOBYB_Post_PGM_RSR_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'EOBYB_Post_PGM_RSR_with_ECC_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'EOBlock_2Page_PGM_AA55_KGD_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'EOBlock_2Page_PGM_DSL_KGD_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'EOBlock_2Page_PGM_F00F_KGD_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'EOBlock_2Page_PGM_FF00_KGD_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'EOBlock_Erase_KGD_(M)', Mode: 'UM ERS', Operation: 'BLK ERS' },
  { Original_Item_Name: 'EOBlock_Erase_RSR_(M)', Mode: 'UM ERS', Operation: 'BLK ERS' },
  { Original_Item_Name: 'EOFast_Read_2Page_AA55_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'EOFast_Read_2Page_DSL_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'EOFast_Read_2Page_F00F_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'EOFast_Read_2Page_FF00_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'EOIcc_Dual_Read_Mhz_KGD_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'EOIcc_Read_Mhz_KGD_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'EOMargin_Read_CKBD_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'EOMargin_Read_CKBD_Dual_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'EOPulse_Page_Program_(M)', Mode: 'TM PGM', Operation: 'PULSE PGM' },
  { Original_Item_Name: 'EOStressWL_(M)', Mode: 'STRESS', Operation: 'WL STRESS' },
  { Original_Item_Name: 'EOStressWL_RBLK_(M)', Mode: 'STRESS', Operation: 'WL STRESS' },
  { Original_Item_Name: 'EOStressWL_wRBLK_4BAM_(M)', Mode: 'STRESS', Operation: 'WL STRESS' },
  { Original_Item_Name: 'EOStressWL_wRBLK_M_(M)', Mode: 'STRESS', Operation: 'WL STRESS' },
  { Original_Item_Name: 'EOStress_Leaky_Row_All_with_RBLK_(M)', Mode: 'STRESS', Operation: 'WL STRESS' },
  { Original_Item_Name: 'EOTM_BE_PerStep_PRE_RSR_(M)', Mode: 'TM ERS', Operation: 'TM BLK ERS' },
  { Original_Item_Name: 'EOTM_BE_PerStep_RSR_(M)', Mode: 'TM ERS', Operation: 'TM BLK ERS' },
  { Original_Item_Name: 'EOTM_BE_PerStep_RSR_4BAM_(M)', Mode: 'TM ERS', Operation: 'TM BLK ERS' },
  { Original_Item_Name: 'EOTM_BE_Refresh_RSR_(M)', Mode: 'TM ERS', Operation: 'TM BLK ERS' },
  { Original_Item_Name: 'EOTM_Skip_SE_Ers_RSR_(M)', Mode: 'TM ERS', Operation: 'PULSE ERS' },
  { Original_Item_Name: 'EOTM_Skip_SE_Ers_RSR_4BAM_(M)', Mode: 'TM ERS', Operation: 'PULSE ERS' },
  { Original_Item_Name: 'EO_Pulse_Sector_Erase_RSR_(M)', Mode: 'TM ERS', Operation: 'TM SEC ERS' },
  { Original_Item_Name: 'EV_IBLK_CAM_only_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'EV_IFR_UID_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'EV_IFR_UID_IBLK_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'EV_IFR_UID_RBLK_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'EV_OptionBit6332_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'EV_OptionBit6332_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'EV_OptionBit9564_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'EV_OptionBit9564_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'EV_OptionBit_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'EV_OptionBit_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'EV_StatusReg_(M)', Mode: 'TM MINI', Operation: 'SR WR' },
  { Original_Item_Name: 'EV_StatusReg_IBLK_(M)', Mode: 'TM MINI', Operation: 'SR WR' },
  { Original_Item_Name: 'Erase_OptionBitNPD_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Erase_OptionBitRSR_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Erase_OptionBitRSR_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Erase_OptionBitRSR_IBLK_Stack_die_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Erase_OptionBitRSR_PMUpu_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Erase_OptionBitRSR_STACK_DIE_retest_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Erase_RefCell1_(M)', Mode: 'REF TUNNING', Operation: 'REF TUNNING' },
  { Original_Item_Name: 'Erase_RefCell_(M)', Mode: 'REF TUNNING', Operation: 'REF TUNNING' },
  { Original_Item_Name: 'Erase_RefCell_EXT_(M)', Mode: 'REF TUNNING', Operation: 'REF TUNNING' },
  { Original_Item_Name: 'Erase_Resume_KGD_(M)', Mode: 'TM ERS', Operation: 'PULSE ERS' },
  { Original_Item_Name: 'Even_Odd_BL_Drain_Stress_Leaky_Col_All_(M)', Mode: 'STRESS', Operation: 'BL STRESS' },
  { Original_Item_Name: 'FAG089_CKBD_DR_Check_SHARE_(M)', Mode: 'DR', Operation: 'DR' },
  { Original_Item_Name: 'FR4B0B_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'FR4B0C_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'FX3B0B1_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'FX3B0B2_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'FX3B0BI_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'FX3B0B_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'FX3B0B_CR_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'FX3B0B_idle_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_2BYTE_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_2Page_AA55_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_2Page_DSL_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_2Page_F00F_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_2Page_FF00_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_CKBD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_CR_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_Dual_(M)', Mode: 'UM READ', Operation: 'DUAL READ' },
  { Original_Item_Name: 'Fast_Read_ECC_KGD_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Fast_Read_FF000000_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_NByte_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_RDM_Range_DATA_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_Range_CKBD_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_Range_CKBD_KGD_WAIT_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_Range_CKBD_SUS_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_Range_DATA_KGD_9966_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_Range_DIO0X_CKBD_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_Range_DIOAX_CKBD_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_Range_Dual_CKBD_KGD_(M)', Mode: 'UM READ', Operation: 'DUAL READ' },
  { Original_Item_Name: 'Fast_Read_Range_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_Range_SIO0X_CKBD_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Fast_Read_Range_SIOAX_CKBD_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Global_Block_Lock_KGD_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Global_Block_Unlock_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Global_Block_unLock_KGD_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'HBlock_Erase_KGD_(M)', Mode: 'UM ERS', Operation: 'HBLK ERS' },
  { Original_Item_Name: 'HBlock_Erase_RSR_(M)', Mode: 'UM ERS', Operation: 'HBLK ERS' },
  { Original_Item_Name: 'IBLK_Page_Program_55aa_RSR_KGD_(M)', Mode: 'UM MINI', Operation: 'IBLK WR' },
  { Original_Item_Name: 'IBLK_Page_Program_55aa_RSR_KGD_4PAGE_(M)', Mode: 'UM MINI', Operation: 'IBLK WR' },
  { Original_Item_Name: 'IBLK_Page_Program_CKBD_RSR_KGD_(M)', Mode: 'UM MINI', Operation: 'IBLK WR' },
  { Original_Item_Name: 'IBLK_Page_Program_CKBD_RSR_KGD_4PAGE_(M)', Mode: 'UM MINI', Operation: 'IBLK WR' },
  { Original_Item_Name: 'IBLK_Pulse_SoftPGM_RSR_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'IBLK_Read_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'IBLK_Read_KGD_4PAGE_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'IBLK_Read_Range_55aa_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'IBLK_Read_Range_55aa_KGD_4PAGE_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'IBLK_Read_Range_CKBD_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'IBLK_Read_Range_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'IO_Stress_New_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Icc_PWD_250UA_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Icc_PWD_New_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Icc_PWD_New_LT_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Icc_Read_33Mhz_New_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Icc_SB_250UA_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Icc_SB_CMOS_Stree_M_New_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Icc_SB_New_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Icc_SB_New_1_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Icc_SB_POR_New_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Individual_Block_Lock_KGD_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Individual_Block_unLock_KGD_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Individual_SectorBlk_Lock_KGD_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Individual_SectorBlk_unLock_KGD_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Individual_Sector_Lock_KGD_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Individual_Sector_unLock_KGD_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'InputLeakageHi_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'InputLeakageLow_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'JEDEC_ID_(M)', Mode: 'ID', Operation: 'ID READ' },
  { Original_Item_Name: 'JEDEC_ID_KGD_(M)', Mode: 'ID', Operation: 'ID READ' },
  { Original_Item_Name: 'LKBT36_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'LKBT39_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'LKBT7E_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'LKBT98_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Leaky_Row_All_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Leaky_Row_All_DS00_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Leaky_Row_All_RBLK_Only_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Leaky_Row_All_RBLK_Only_4BAM_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Leaky_Row_All_with_RBLK_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Leaky_Row_All_with_RBLK_4BAM_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Leaky_Row_RBLK_By_4MBlock_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'MAIN_Program_FT_Data_RSR_KGD_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'MAIN_Read_FT_Data_RSR_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'MR_Distribution_FUSE_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read2B_CKBD_Dual_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_1PagePSofBank_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_1PagePSofBank_4BAM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_1PagePerBank_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_1PagePerEvenSec_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_2Byte_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_2Byte_T_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_2byte_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_3X_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_40MHz_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_4BAM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_4BAM_AFM_(M)', Mode: 'MR', Operation: 'MR AFM' },
  { Original_Item_Name: 'Margin_Read_AFM_(M)', Mode: 'MR', Operation: 'MR AFM' },
  { Original_Item_Name: 'Margin_Read_AFM_Dual_(M)', Mode: 'MR', Operation: 'MR AFM' },
  { Original_Item_Name: 'Margin_Read_BA_BELoop_R11_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_BA_BELoop_R11_4BAM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_CKBD_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_CKBD_1PagePerEvenSec_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_CKBD_AFM_(M)', Mode: 'MR', Operation: 'MR AFM' },
  { Original_Item_Name: 'Margin_Read_CKBD_AFM_Dual_(M)', Mode: 'MR', Operation: 'MR AFM' },
  { Original_Item_Name: 'Margin_Read_CKBD_AFM_MultiVG_(M)', Mode: 'MR', Operation: 'MR AFM' },
  { Original_Item_Name: 'Margin_Read_CKBD_Dual_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_CKBD_Dual_AFM_MultiVG_(M)', Mode: 'MR', Operation: 'MR AFM' },
  { Original_Item_Name: 'Margin_Read_CKBD_Dual_MultiVG_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_CKBD_IBLK_(M)', Mode: 'MR', Operation: 'MR IBLK' },
  { Original_Item_Name: 'Margin_Read_CKBD_IBLK_4PAGE_(M)', Mode: 'MR', Operation: 'MR IBLK' },
  { Original_Item_Name: 'Margin_Read_CKBD_MultiVG_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_CKBD_NR_ECC_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_CKBD_NR_ECC_4BAM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_CKBD_NR_ECC_MultiVG_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_CKBD_NR_ECC_MultiVG_4BAM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_Dual_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_Dual_1PagePSofBank_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_Dual_1PagePerBank_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_Dual_AFM_MultiVG_GM_(M)', Mode: 'MR', Operation: 'MR AFM' },
  { Original_Item_Name: 'Margin_Read_Dual_BA_BELoop_R11_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_Dual_LGM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_Dual_LGMwithSRAM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_Dual_MultiVG_GM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_Fuse_SR4_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_IBLK_(M)', Mode: 'MR', Operation: 'MR IBLK' },
  { Original_Item_Name: 'Margin_Read_IBLK_4BAM_(M)', Mode: 'MR', Operation: 'MR IBLK' },
  { Original_Item_Name: 'Margin_Read_IBLK_4PAGE_(M)', Mode: 'MR', Operation: 'MR IBLK' },
  { Original_Item_Name: 'Margin_Read_LGM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_LGMwithSRAM_4BAM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_MultiVG_GM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_MultiVG_GM_AFM_(M)', Mode: 'MR', Operation: 'MR AFM' },
  { Original_Item_Name: 'Margin_Read_MultiVG_LGM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_NR_ECC_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_NR_LGM_ECC_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_NR_MultiVG_GM_ECC_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_NR_SRAMLGM_ECC_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_R11_1PagePerEvenSec_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_R11_1PagePerEvenSec_4BAM_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_R11_1PagePerEvenSec_unsel_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_Read_T_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_SRAMLGM_Read_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Margin_SRAMLGM_Read_AFM_(M)', Mode: 'MR', Operation: 'MR AFM' },
  { Original_Item_Name: 'Margin_SRAMLGM_Read_Dual_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'Measure_Cell_Current_(M)', Mode: 'MONITOR', Operation: 'MONITOR' },
  { Original_Item_Name: 'Measure_Cell_Current_All_(M)', Mode: 'MONITOR', Operation: 'MONITOR' },
  { Original_Item_Name: 'Measure_RefCell_All1_(M)', Mode: 'REF TUNNING', Operation: 'REF TUNNING' },
  { Original_Item_Name: 'Measure_RefCell_All_(M)', Mode: 'REF TUNNING', Operation: 'REF TUNNING' },
  { Original_Item_Name: 'Measure_RefCell_All_4BAM_(M)', Mode: 'REF TUNNING', Operation: 'REF TUNNING' },
  { Original_Item_Name: 'Measure_VPPD_(M)', Mode: 'MONITOR', Operation: 'MONITOR' },
  { Original_Item_Name: 'Measure_VPPI_(M)', Mode: 'MONITOR', Operation: 'MONITOR' },
  { Original_Item_Name: 'Measure_VPPI_EBulk_(M)', Mode: 'MONITOR', Operation: 'MONITOR' },
  { Original_Item_Name: 'Monitor_Safe_Boot_(M)', Mode: 'MONITOR', Operation: 'MONITOR' },
  { Original_Item_Name: 'NR4B13_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'NVCR_Read_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'NX3B032_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'NX3B03_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'NX3B03_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'NX3B03_PA_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'NX4B03_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Narrow_PGM_Vt_(M)', Mode: 'TM PGM', Operation: 'PULSE PGM' },
  { Original_Item_Name: 'Negative_Gate_Stress_EXTTIME_(M)', Mode: 'STRESS', Operation: 'NG STRESS' },
  { Original_Item_Name: 'Negative_Gate_Stress_extT_All_(M)', Mode: 'STRESS', Operation: 'NG STRESS' },
  { Original_Item_Name: 'Normal_Read_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Normal_Read_1_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Normal_Read_CR_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Normal_Read_Diag_Code_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Normal_Read_ECC_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Normal_Read_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Normal_Read_RDM_Range_DATA_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Normal_Read_Range_CKBD_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Normal_Read_Range_Code_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Normal_Read_Range_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Normal_Read_Range_SlewRate_CKBD_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Normal_SlewRate_Read_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'Opens_PE_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Opens_POR_New_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Opens_PPS_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'OptionBit6332_PV_PGM_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'OptionBit6332_PV_PGM_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'OptionBit6332_PV_PGM_PMUpu_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'OptionBit8864_PV_PGM_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'OptionBit8864_PV_PGM_PMUpu_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'OptionBit9564_PV_PGM_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'OptionBit9564_PV_PGM_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'OptionBit_EV_ERS_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'OptionBit_EV_ERS_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'OptionBit_EV_ERS_PMUpu_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'OptionBit_PV_PGM_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'OptionBit_PV_PGM_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'OptionBit_PV_PGM_PMUpu_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'OutputLeakageHi_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'OutputLeakageLow_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'PG3X02_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'PI3B42_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'PV_IFR_UID_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'PV_IFR_UID_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'PV_OptionBit6332_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'PV_OptionBit6332_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'PV_OptionBit8864_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'PV_OptionBit9564_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'PV_OptionBit9564_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'PV_OptionBit_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'PV_OptionBit_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'PV_StatusReg_(M)', Mode: 'TM MINI', Operation: 'SR WR' },
  { Original_Item_Name: 'Page_PGM_SRAM_Check_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'Page_Program_2byte_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Page_Program_FF000000_KGD_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Page_program_Suspend_Resume_KGD_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Positive_Gate_Stress_(M)', Mode: 'STRESS', Operation: 'WL STRESS' },
  { Original_Item_Name: 'Positive_Gate_Stress_10ms_(M)', Mode: 'STRESS', Operation: 'WL STRESS' },
  { Original_Item_Name: 'Positive_Gate_Stress_10ms_RBLK_(M)', Mode: 'STRESS', Operation: 'WL STRESS' },
  { Original_Item_Name: 'Positive_Gate_Stress_PMU_Loop_(M)', Mode: 'STRESS', Operation: 'WL STRESS' },
  { Original_Item_Name: 'Positive_Gate_Stress_PMU_Loop_RBLK_(M)', Mode: 'STRESS', Operation: 'WL STRESS' },
  { Original_Item_Name: 'Positive_Gate_Stress_with_RBLK_(M)', Mode: 'STRESS', Operation: 'WL STRESS' },
  { Original_Item_Name: 'Program_IFR_UID_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Program_IFR_UID_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Program_IFR_UID_IBLK_XVPPI_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Pulse_1st_WL_PerBank_PGM_CKBD_DS00_(M)', Mode: 'TM PGM', Operation: 'PULSE PGM' },
  { Original_Item_Name: 'Pulse_Auto_EOPre_PGM_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Auto_EOPre_PGM_with_ECC_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Auto_Pre_PGM_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Auto_Pre_PGM_With_ECC_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Auto_Pre_PGM_With_ECC_4BAM_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Auto_PstPrePGM_RSR_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_CE_XVPPI_M_(M)', Mode: 'TM ERS', Operation: 'PULSE ERS' },
  { Original_Item_Name: 'Pulse_Chip_Erase_Loop_(M)', Mode: 'TM ERS', Operation: 'PULSE ERS' },
  { Original_Item_Name: 'Pulse_Chip_Erase_RSR_(M)', Mode: 'TM ERS', Operation: 'PULSE ERS' },
  { Original_Item_Name: 'Pulse_Erase_OptionBitRSR_IBLK_WL_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'Pulse_Erase_WLtoBL_Stress_(M)', Mode: 'TM ERS', Operation: 'PULSE ERS' },
  { Original_Item_Name: 'Pulse_Erase_XVPPI_RBLK_Chip_TWC_(M)', Mode: 'TM ERS', Operation: 'PULSE ERS' },
  { Original_Item_Name: 'Pulse_Erase_XVPPI_RBLK_Chip_TWC_4BAM_(M)', Mode: 'TM ERS', Operation: 'PULSE ERS' },
  { Original_Item_Name: 'Pulse_Erase_XVPPI_TWC_(M)', Mode: 'TM ERS', Operation: 'PULSE ERS' },
  { Original_Item_Name: 'Pulse_IBLK_SoftPGM_RSR_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'Pulse_PSTPGM_RBLK_RSR_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'Pulse_PSTPGM_RBLK_RSR_4BAM_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'Pulse_Page_PGM_CKBD_(M)', Mode: 'TM PGM', Operation: 'PULSE PGM' },
  { Original_Item_Name: 'Pulse_Page_PGM_CKBD_With_ECC_(M)', Mode: 'TM PGM', Operation: 'PULSE PGM' },
  { Original_Item_Name: 'Pulse_Pre_PGM_RBLK_ALL_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Pre_PGM_RBLK_ALL_4BAM_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Pre_PGM_RSR_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Pre_PGM_RSR_4BAM_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Pre_PGM_RSR_With_ECC_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_PstPrePGM_RSR_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_RDN_PstPrePGM_RSR_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Red_Auto_PGM_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Red_Auto_Pre_PGM_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Red_Auto_Pre_PGM_4BAM_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Red_Auto_Pre_PGM_RBLK_ALL_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_Red_Auto_Pre_PGM_RBLK_ALL_4BAM_(M)', Mode: 'TM PGM', Operation: 'PRE PGM' },
  { Original_Item_Name: 'Pulse_SoftPGM_RSR_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'Pulse_SoftPGM_RSR_4BAM_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'Pulse_SoftPGM_RSR_Skip_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'Pulse_SoftPGM_RSR_Skip_4BAM_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'Pulse_SoftPGM_RSR_UBM_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'Pulse_SoftPGM_RSR_With_ECC_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'Q16EB1_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3080B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3080E_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3180B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3A20C_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3A40C_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3A60C_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3A80C_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3BS02_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X10EB_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X12EB_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X14EB_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X16EB_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X20B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X2EB_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X40B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X4EB_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X60B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X6EB_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X6EB_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X80B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X8EB_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q3X8EB_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q4220C_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q4240C_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q4241U_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q4260C_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q4261U_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q4280C_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q4BEB1_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Q4BEB4_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QB3S20_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QB3S52_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QE21EC_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QIOMID_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QP0604_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QP1DFF_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QP2WFF_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QP3B32_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QP3B32_PA1_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QP3B32_PA_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QP3B32_idle_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QP3B32_idle_PA_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QP4B34_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QPIR69_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR3X6B1_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR3X6B2_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR3X6B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR3X6B_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR3XEB1_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR3XEB1_91_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR3XEB2_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR3XEB2_91_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR3XEBA_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR3XEBI_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR3XEB_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR3XEB_CR_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR3XEB_idle_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR4B6B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR4B6C_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR4BEB_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QR4BEC_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QRA3EBA_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QRA3EB_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QRA4EB_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QREE7A_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QREP7A_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QRID90_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QRID9F_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QRIDAB_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QRST05_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QRST15_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QRST35_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QS1E75_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QS1P75_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QSUE75_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QSUP75_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QWST01_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QWST11_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QWST31_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QWST501_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QWST502_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'QWST503_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'RBLK_CAM_PGM_PV_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'RBLK_Repair_Analysis_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'RDJEID_(M)', Mode: 'ID', Operation: 'ID READ' },
  { Original_Item_Name: 'RDLKBTB_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'RDLKBT_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'RDMFID_(M)', Mode: 'ID', Operation: 'ID READ' },
  { Original_Item_Name: 'RDN_Margin_Read_CKBD_ECR1_(M)', Mode: 'MR', Operation: 'MR RDN' },
  { Original_Item_Name: 'RDN_Margin_Read_CKBD_ECR1_4BAM_(M)', Mode: 'MR', Operation: 'MR RDN' },
  { Original_Item_Name: 'RDN_Margin_Read_CKBD_MultiVg_ECR1_(M)', Mode: 'MR', Operation: 'MR RDN' },
  { Original_Item_Name: 'RDN_Margin_Read_CKBD_MultiVg_ECR1_4BAM_(M)', Mode: 'MR', Operation: 'MR RDN' },
  { Original_Item_Name: 'RDN_Margin_Read_ECR1_(M)', Mode: 'MR', Operation: 'MR RDN' },
  { Original_Item_Name: 'RDN_Margin_Read_ECR1_4BAM_(M)', Mode: 'MR', Operation: 'MR RDN' },
  { Original_Item_Name: 'RDN_Margin_Read_LGM_(M)', Mode: 'MR', Operation: 'MR RDN' },
  { Original_Item_Name: 'RDN_Margin_Read_LGMwithSRAM_(M)', Mode: 'MR', Operation: 'MR RDN' },
  { Original_Item_Name: 'RDN_Margin_Read_MultiVG_ECR1_LGM_(M)', Mode: 'MR', Operation: 'MR RDN' },
  { Original_Item_Name: 'RDN_Margin_Read_MultiVG_GM_(M)', Mode: 'MR', Operation: 'MR RDN' },
  { Original_Item_Name: 'RDN_Margin_SRAMLGM_Read_ECR1_(M)', Mode: 'MR', Operation: 'MR RDN' },
  { Original_Item_Name: 'RDN_Pst_PGM_RBLK_RSR_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'RDN_Pst_PGM_RBLK_RSR_ALL_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'RDN_Pst_PGM_RBLK_RSR_ALL_4BAM_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'RDN_Pst_PGM_RSR_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'RDN_Pst_PGM_RSR_4BAM_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'RDN_Pst_PGM_RSR_NOBbB_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'REDSTT_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'RESB7A_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'RI3B48_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'RPWDID_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'RSTWELC5_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'RSTWEL_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Range_FullPage_PGM_CKBD_KGD_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'ReadBack_CAMInfo_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackCAM' },
  { Original_Item_Name: 'ReadBack_CAMInfo_DR_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackCAM' },
  { Original_Item_Name: 'ReadBack_CAMInfo_DR_AAG070_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackCAM' },
  { Original_Item_Name: 'ReadBack_CAMInfo_DR_Check_IBLK_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackCAM' },
  { Original_Item_Name: 'ReadBack_CAMInfo_DR_FAG089_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackCAM' },
  { Original_Item_Name: 'ReadBack_CAMInfo_DR_Finial_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackCAM' },
  { Original_Item_Name: 'ReadBack_CAMInfo_DR_IBLK_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackCAM' },
  { Original_Item_Name: 'ReadBack_CAMInfo_DR_IBLK_RBLK_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackCAM' },
  { Original_Item_Name: 'ReadBack_CAMInfo_ShowOnly_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackCAM' },
  { Original_Item_Name: 'ReadBack_CAMInfo_onlyread_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackCAM' },
  { Original_Item_Name: 'ReadBack_CAMInfo_onlyread_IBLK_check_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackCAM' },
  { Original_Item_Name: 'ReadBack_CAMInfo_onlyread_check_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackCAM' },
  { Original_Item_Name: 'ReadBack_IFRUID_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'ReadBack_IFRUID_IBLK_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'ReadBack_NVCR_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'ReadBack_OPTION_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'Read_Block_Lock_KGD_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Read_Block_Lock_KGD_LOOP_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Read_SectorBlk_Lock_ALL_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Read_SectorBlk_Lock_KGD_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Read_Sector_Lock_KGD_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Read_Sector_Lock_KGD_LOOP_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Recover_Over_ERS_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'Recover_Over_ERS_RBLK_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'Recover_Over_ERS_RBLK_RDN_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'Recover_Over_ERS_RDN_(M)', Mode: 'TM PGM', Operation: 'PST PGM' },
  { Original_Item_Name: 'RefCell_Measure_Erase1_(M)', Mode: 'REF TUNNING', Operation: 'REF TUNNING' },
  { Original_Item_Name: 'RefCell_Measure_Erase_(M)', Mode: 'REF TUNNING', Operation: 'REF TUNNING' },
  { Original_Item_Name: 'RefCell_Measure_Erase_4BAM_(M)', Mode: 'REF TUNNING', Operation: 'REF TUNNING' },
  { Original_Item_Name: 'Release_PWD_ID_Read_KGD_(M)', Mode: 'ID', Operation: 'ID READ' },
  { Original_Item_Name: 'Repair_Algorithm_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Algorithm_4BAM2_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Algorithm_CAT1M_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Algorithm_CAT3L_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Algorithm_CAT3Q_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Algorithm_CAT6E_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Algorithm_CAT6E_1_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Algorithm_CAT6E_4BAM2_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Algorithm_CAT6E_4BAM_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Algorithm_Cat3L_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Algorithm_DR_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Algorithm_ERS_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Algorithm_TestChip_CAT6E_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Algorithm_cat3L_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Analysis_(M)', Mode: 'CAM WR', Operation: 'CAM WR' },
  { Original_Item_Name: 'Repair_Leaky_Row_Algorithm_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'S1P1_Final_OptionBit_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'S1P1_Final_OptionBit_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'S1P1_IFR_Mark_IBLK_MDUT_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'S1P1_IFR_Mark_MDUT_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'S1P1_Pass_Mark_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'S1P1_ReFresh_OptionBit_IFR_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'S1P1_XY_IFR_Mark_MDUT_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'SE_1st_PreBank_RSR_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'SE_1st_PreBank_RSR_4BAM_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'SE_63st_PreBank_RSR_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'SE_63st_PreBank_RSR_4BAM_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'SFDP_Program_FT_Data_RSR_KGD_(M)', Mode: 'UM MINI', Operation: 'SFDP WR' },
  { Original_Item_Name: 'SFDP_Read_FT_Data_RSR_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'SFIN_ALL0_DR_Outlier_Check_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
  { Original_Item_Name: 'SFIN_Fail_Retest_(M)', Mode: 'FAIL RETEST', Operation: 'FAIL RETEST' },
  { Original_Item_Name: 'SFIN_IFR_Mark_IBLK_MDUT_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'SFIN_IFR_Mark_MDUT_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'SFIN_Pass_Mark_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'SFIN_ReFresh_OptionBit_IFR_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'SFIN_ReFresh_OptionBit_IFR_Finial_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'SFIN_ReFresh_OptionBit_IFR_IBLK_Final_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'SFIN_ReFresh_OptionBit_IFR_ReVPPI_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'SPRE_CKBD0_Outlier_(M)', Mode: 'MR', Operation: 'MR' },
  { Original_Item_Name: 'SPRE_IFR_Mark_IBLK_MDUT_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'SPRE_IFR_Mark_MDUT_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'SPRE_Pass_Mark_(M)', Mode: 'CHECK INFO', Operation: 'ReadPassMark' },
  { Original_Item_Name: 'SPRE_ReFresh_OptionBit_IFR_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'SPRE_ReFresh_OptionBit_IFR_IBLK_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'SPRE_ReFresh_OptionBit_IFR_IBLK_Final_(M)', Mode: 'OPTION WR', Operation: 'OPTION WR' },
  { Original_Item_Name: 'SRAM_Setup_31_0_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'SRAM_Setup_63_0_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'SRAM_Setup_71_0_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'SRAM_Setup_71_0_DIE_SELECT_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'SRAM_Setup_79_0_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'SRAM_Setup_79_0_PMUpu_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'SRAM_Setup_87_0_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'SRAM_Setup_95_0_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'SRAM_Setup_95_0_Refcell_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'SRAM_Setup_95_0_Stack_die_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'SRAM_Setup_Byte_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'SRAM_Setup_Byte_Narrow_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'SRAM_Setup_Refresh_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'SRAM_Setup_SR_(M)', Mode: 'OPTION SRAM', Operation: 'OPTION SRAM' },
  { Original_Item_Name: 'STWHQZ_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'SUSB75_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Sector_Erase_CR_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Sector_Erase_RSR_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Sector_Erase_RSR_4BAM_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Sector_Erase_Skip_RSR_N_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Sector_Erase_Suspend_CR_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Sector_Erase_Suspend_KGD_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Sector_Erase_Suspend_KGD_SUS_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Sector_Erase_Suspend_SUS20_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Sector_Erase_WhenSUS_KGD_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Sector_Range_Erase_KGD_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Sector_Range_Erase_RSR_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Security_Erase_RSR_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Security_Erase_RSR_KGD_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Shorts_Check_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Shorts_Check_HT_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'Shorts_PPS_(M)', Mode: 'DC', Operation: 'DC' },
  { Original_Item_Name: 'StatusReg1_Read_KGD_WREN_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'StatusReg_Read_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'StatusReg_Read_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'StatusReg_Read_KGD_NOPD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'StatusReg_Read_POR_KGD_(M)', Mode: 'UM READ', Operation: 'SPI READ' },
  { Original_Item_Name: 'StatusReg_Write_(M)', Mode: 'UM MINI', Operation: 'SR WR' },
  { Original_Item_Name: 'StatusReg_Write_KGD_(M)', Mode: 'UM MINI', Operation: 'SR WR' },
  { Original_Item_Name: 'StatusReg_Write_KGD_NOPD_(M)', Mode: 'UM MINI', Operation: 'SR WR' },
  { Original_Item_Name: 'StatusReg_Write_PMUpu_(M)', Mode: 'UM MINI', Operation: 'SR WR' },
  { Original_Item_Name: 'StatusReg_Write_SR1_(M)', Mode: 'UM MINI', Operation: 'SR WR' },
  { Original_Item_Name: 'Status_Register_Read_loop_(M)', Mode: 'UM MINI', Operation: 'SR WR' },
  { Original_Item_Name: 'TMStatusReg_Write_Skip_(M)', Mode: 'TM MINI', Operation: 'SR WR' },
  { Original_Item_Name: 'TM_Block_Erase_PerStep_Bank_(M)', Mode: 'TM ERS', Operation: 'TM BLK ERS' },
  { Original_Item_Name: 'TM_Block_Erase_PerStep_Bank_4BAM_(M)', Mode: 'TM ERS', Operation: 'TM BLK ERS' },
  { Original_Item_Name: 'TM_Block_Erase_PerStep_Well_(M)', Mode: 'TM ERS', Operation: 'TM BLK ERS' },
  { Original_Item_Name: 'TM_Block_Erase_PerStep_Well_4BAM_(M)', Mode: 'TM ERS', Operation: 'TM BLK ERS' },
  { Original_Item_Name: 'TM_CE_SkipPre_RSR_(M)', Mode: 'TM ERS', Operation: 'TM BLK ERS' },
  { Original_Item_Name: 'TM_Diag_Page_Program_58S_(M)', Mode: 'TM PGM', Operation: 'PULSE PGM' },
  { Original_Item_Name: 'TM_Die_Select_PMUpu_(M)', Mode: 'UM MINI', Operation: 'SR WR' },
  { Original_Item_Name: 'TM_NVCR_Read_(M)', Mode: 'TM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'TM_Refresh_RSR_(M)', Mode: 'TM ERS', Operation: 'TM BLK ERS' },
  { Original_Item_Name: 'TM_SE_1st_PreBank_RSR_(M)', Mode: 'TM ERS', Operation: 'TM SEC ERS' },
  { Original_Item_Name: 'TM_SE_63st_PreBank_RSR_(M)', Mode: 'TM ERS', Operation: 'TM SEC ERS' },
  { Original_Item_Name: 'TM_Sector_Erase_RSR_(M)', Mode: 'TM ERS', Operation: 'TM SEC ERS' },
  { Original_Item_Name: 'TM_Write_NVCR_(M)', Mode: 'TM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'TRS1ID_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'TRS2ID_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Tune_Dual_RefCell_(M)', Mode: 'REF TUNNING', Operation: 'REF TUNNING' },
  { Original_Item_Name: 'Tune_RefCell_(M)', Mode: 'REF TUNNING', Operation: 'REF TUNNING' },
  { Original_Item_Name: 'Tune_VBGR_(M)', Mode: 'BIAS TUNNING', Operation: 'BIAS TUNNING' },
  { Original_Item_Name: 'Tune_VPPI_(M)', Mode: 'BIAS TUNNING', Operation: 'BIAS TUNNING' },
  { Original_Item_Name: 'Tune_Vref_(M)', Mode: 'BIAS TUNNING', Operation: 'BIAS TUNNING' },
  { Original_Item_Name: 'Tune_Vref_DS00_(M)', Mode: 'BIAS TUNNING', Operation: 'BIAS TUNNING' },
  { Original_Item_Name: 'UM_Write_NVCR_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'UnLock_Write_NVCR2_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'UnLock_Write_SR1_090_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'UnLock_Write_SR2_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'UnLock_Write_SR2_090_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'UnLock_Write_SR2_PMUpu_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'UnLock_Write_SR_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'UnLock_Write_SR_PMUpu_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'UnLock_Write_SR_skip_(M)', Mode: 'UM MINI', Operation: 'LOCK WR' },
  { Original_Item_Name: 'Unique_ID_NEW_(M)', Mode: 'ID', Operation: 'ID READ' },
  { Original_Item_Name: 'Unique_ID_PN_KGD_(M)', Mode: 'ID', Operation: 'ID READ' },
  { Original_Item_Name: 'Unlock_Sector_Erase_RSR_SDUT_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'Unlock_Sector_Erase_RSR_SDUT_KGD_(M)', Mode: 'UM ERS', Operation: 'SEC ERS' },
  { Original_Item_Name: 'WR5031_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WR5035_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRAPEB_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRAPEC_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRPHEB16B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRPHEB32B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRPHEB64B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRPHEB8B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRPHEC16B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRPHEC32B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRPHEC64B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRPHEC8B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRPHED16B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRPHED32B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRPHED64B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRPHED8B_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRSTAC_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRSTWH_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WRTSTT_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'WST50H_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'Well_Stress_MRI1_(M)', Mode: 'STRESS', Operation: 'WELL STRESS' },
  { Original_Item_Name: 'Well_Stress_Multi_(M)', Mode: 'STRESS', Operation: 'WELL STRESS' },
  { Original_Item_Name: 'Well_Stress_Multi_with_RBLK_(M)', Mode: 'STRESS', Operation: 'WELL STRESS' },
  { Original_Item_Name: 'Well_Stress_with_RBLK_(M)', Mode: 'STRESS', Operation: 'WELL STRESS' },
  { Original_Item_Name: 'Well_Stress_with_RBLK_4BAM_(M)', Mode: 'STRESS', Operation: 'WELL STRESS' },
  { Original_Item_Name: 'Whole_Page_2byte_Program_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Whole_Page_PGM_CKBD_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Whole_Page_PGM_CKBD_KGD_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Whole_Page_PGM_CKBD_With_ECC_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Whole_Page_PGM_CKBD_With_ECC_4BAM_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Whole_Page_PGM_IBLK_CKBD_(M)', Mode: 'UM MINI', Operation: 'IBLK WR' },
  { Original_Item_Name: 'Whole_Page_PGM_IBLK_CKBD_4PAGE_(M)', Mode: 'UM MINI', Operation: 'IBLK WR' },
  { Original_Item_Name: 'Whole_Page_PGM_SlewRate_CKBD_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Whole_Page_PGM_SlewRate_CKBD_Feat_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Whole_Page_Program_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Whole_Page_Program_1_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Whole_Page_Program_CR_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'Whole_Page_Program_WT_(M)', Mode: 'UM PGM', Operation: 'PGM' },
  { Original_Item_Name: 'XE3B20_(M)', Mode: 'SPEED', Operation: 'SPEED' },
  { Original_Item_Name: 'YSA_Check_FB_(M)', Mode: 'CHECK INFO', Operation: 'ReadBackIFR' },
];
