-- JB Booking Supabase schema
-- Execute in Supabase SQL editor

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  booking_date date not null,
  tester text not null,
  user_name text not null,
  unit text not null,
  start_time text not null,
  end_time text not null,
  client_id text default '',
  created_at timestamptz not null default now()
);

create unique index if not exists ux_appointments_slot
on public.appointments (booking_date, tester, start_time);

alter table public.appointments enable row level security;

-- Demo policy for internal PoC only.
-- Replace with stricter policy before production.
drop policy if exists "Allow anon read/write appointments" on public.appointments;
create policy "Allow anon read/write appointments"
on public.appointments
for all
to anon
using (true)
with check (true);
